### ISSUE TITLE
Rename plugin?

### ISSUE THREAD

**Issue by remcotolsma** [pronamic/wp-pronamic-woocommerce-conditional-payments-suggest#1]
The https://wordpress.org/plugins/plugin-check/ plugin is giving the following warning:

> Error: The readme name includes a restricted term. Your chosen plugin name - `Pronamic WooCommerce Payment Gateways Countries Condition` - contains the restricted term "woocommerce" which cannot be used within in your plugin name, unless your plugin name ends with "for woocommerce". The term must still not appear anywhere else in your name.

Rename this plugin from:

> Pronamic WooCommerce Payment Gateways Countries Condition

to:

> Pronamic Payment Gateways Countries Condition for WooCommerce

?

**Comment by rvdsteege** [comment]
😔 👍
